### ISSUE TITLE
Implement the Main Categories section

### ISSUE THREAD

**Issue by pawan-live** [sliitsesc/rheumaconnect-fe#17]
## Task Summary

- Implement the main categories section with the mobile responsive view as well
- Clicking on a card will take the user to each category page which will have all sub categories

📌 Please refer to "note to developers" blocks in the design file

---

## Acceptance Criteria

- [ ] On hover it should have a border like effect as shown in the design
- [ ] Implemented according to styles/sizes in the design specification
- [ ] The cards should be clickable (don't link them to anywhere, just keep them clickable)
- [ ] The image should be set to cover
- [ ] Load the dummy data from a JSON file (later will be fetched from API)
- [ ] Should be decently responsive for all screen sizes (ex: the cards should not crop out when resized)
- [ ] Implement the mobile design for small breakpoints (until 'md')
- [ ] spacing and padding are properly done as in the design

---

Design files: 
- [desktop](https://www.figma.com/design/Ygf1alhgBbL3IeVSNRQtS7/RheumaConnect-CSR?node-id=398-928&t=wrhOsbtCmTJ2L0F4-4)
- [mobile design](https://www.figma.com/design/Ygf1alhgBbL3IeVSNRQtS7/RheumaConnect-CSR?node-id=595-3342&t=wrhOsbtCmTJ2L0F4-4)
- [note](https://www.figma.com/design/Ygf1alhgBbL3IeVSNRQtS7/RheumaConnect-CSR?node-id=630-2163&t=wrhOsbtCmTJ2L0F4-4)

---

## Additional Information

Desktop view
![image](https://github.com/user-attachments/assets/31ba1d1e-d885-44c9-82d6-73e72a7f9f6f)

Mobile view
![image](https://github.com/user-attachments/assets/16179226-f18a-4895-93f4-59fd3f3c8f6e)
