### ISSUE TITLE
Implement the "Common concerns" section

### ISSUE THREAD

**Issue by pawan-live** [sliitsesc/rheumaconnect-fe#18]
## Task Summary

- This section was designed to display most relevant, trending or a selected set of categories or articles
- It has 6 links, which will lead to either articles or categories
- Implement the both desktop and mobile designs

---

## Acceptance Criteria

- [ ] Should follow design specifications given
- [ ] On hover, the color of the card should change (see first card in the design)
- [ ] Should be clickable, and opens a link (for now keep the link blank)
- [ ] For now, use the icons in the design (export as svg)
- [ ] Store the data in a JSON file for now, including icon paths
- [ ] Should be decently responsive on all screen sizes
- [ ] Mobile screen until 'md' breakpoint, after that desktop screen

---

Design files: 
- [desktop design](https://www.figma.com/design/Ygf1alhgBbL3IeVSNRQtS7/RheumaConnect-CSR?node-id=398-950&t=wrhOsbtCmTJ2L0F4-4)
- [mobile design](https://www.figma.com/design/Ygf1alhgBbL3IeVSNRQtS7/RheumaConnect-CSR?node-id=595-3240&t=wrhOsbtCmTJ2L0F4-4)

---

## Additional Information

Desktop
![image](https://github.com/user-attachments/assets/43115d27-901a-4feb-992b-a676d36cb893)

Mobile
![image](https://github.com/user-attachments/assets/4239fa88-7688-428e-8456-d6d435697bba)

**Comment by prb-dev** [comment]
I'll take this

**Comment by pawan-live** [comment]
> I'll take this

Nice!

**Comment by prb-dev** [comment]
In the mobile view, users need to kind of tap and hold to see the highlight effect since mobile devices don’t support the hover feature.

The same font size, weight, and line-height specified in the design were followed. Could someone update the design? I'll update the code accordingly.
