### ISSUE TITLE
Implement the navbar component

### ISSUE THREAD

**Issue by mrmihi** [sliitsesc/rheumaconnect-fe#2]
## Task Summary

- Create the navbar component of the webapp
- Implement the mobile designs as well
- Mobile navbar -> until "md" breakpoint (tailwind default breakpoints)
- Desktop navbar -> after "md" breakpoint
- Use tailwind default container class for container

Note: the language switch button will be implemented in a separate user story so avoid it

---

## Acceptance Criteria

- [ ] Should be mobile responsive (fluid) for the given breakpoints
- [ ] Follow the styles/sizing provided in the figma design
- [ ] The mobile dropdown should appear on hamburger icon click
- [ ] Clicking on the background should close the mobile navbar dropdown menu
- [ ] Desktop navbar: the current page should be underlined or displayed in a different color

---

Design files: 
- [link 1](https://www.figma.com/design/Ygf1alhgBbL3IeVSNRQtS7/RheumaConnect-CSR?node-id=398-905&t=Dyzpm6vZj01HWXPl-4)
- [link 2](https://www.figma.com/design/Ygf1alhgBbL3IeVSNRQtS7/RheumaConnect-CSR?node-id=509-419&t=Dyzpm6vZj01HWXPl-4)

---

## Additional Information

Desktop navbar
![image](https://github.com/user-attachments/assets/5b10e565-3330-47d3-9477-a077d1690e9b)

Mobile navbar
![image](https://github.com/user-attachments/assets/0562cfd7-483e-49b7-b042-68bcba4d57fb)

Mobile navbar with dropdown open
![image](https://github.com/user-attachments/assets/99360d9b-899e-49bf-be44-106dd492b73b)

**Comment by IT21182914** [comment]
I will take this issue
