### ISSUE TITLE
Implement the "all articles" cards (A-Z cards)

### ISSUE THREAD

**Issue by pawan-live** [sliitsesc/rheumaconnect-fe#20]
## Task Summary

- These cards, when clicked, will redirect the user to an "all articles" in a specific category
- Implement the desktop and mobile design

---

## Acceptance Criteria

- [ ] Should be clickable (keep the links blank for now)
- [ ] Hover effect should be implemented
- [ ] Should follow design specification given
- [ ] Should be mobile responsive ("md" breakpoint)
- [ ] Should be decently responsive in all screen sizes

---

Design files: 
- [desktop design](https://www.figma.com/design/Ygf1alhgBbL3IeVSNRQtS7/RheumaConnect-CSR?node-id=398-1026&t=wrhOsbtCmTJ2L0F4-4)
- [mobile design](https://www.figma.com/design/Ygf1alhgBbL3IeVSNRQtS7/RheumaConnect-CSR?node-id=612-131&t=wrhOsbtCmTJ2L0F4-4)

---

## Additional Information

Desktop
![image](https://github.com/user-attachments/assets/7163dbf3-b2db-4b59-a54e-9c261364ac2c)

Mobile
![image](https://github.com/user-attachments/assets/8ebe3c5b-93c5-4d32-a627-e7d99197de63)

**Comment by saputhebeast** [comment]
Can I work on this task?

**Comment by pawan-live** [comment]
> Can I work on this task? @pawan-live

Sure thanks, will assign
