### ISSUE TITLE
Implement the "Seek medicak help" section

### ISSUE THREAD

**Issue by pawan-live** [sliitsesc/rheumaconnect-fe#21]
## Task Summary

- The contact hospital section contains essential information about the relevant hospital which the system is based in
- It suggests users to contact hospital in an emergency situation rather than relying on the site
- Implement both desktop and mobile views

---

## Acceptance Criteria

- [ ] The contact card should be clickable and should open the dialer if on the phone with the given phone number to call
- [ ] If on a desktop device do the same, still the phone number should be displayed
- [ ] The contact links should be clickable
- [ ] Should match the design specifications given
- [ ] Should be mobile responsive ("md" brakpoint)
- [ ] Should be decently responsive on any screen size
- [ ] Later on, more contact options will be added

---

Design files: 
- [desktop design](https://www.figma.com/design/Ygf1alhgBbL3IeVSNRQtS7/RheumaConnect-CSR?node-id=398-1066&t=wrhOsbtCmTJ2L0F4-4)
- [mobile design](https://www.figma.com/design/Ygf1alhgBbL3IeVSNRQtS7/RheumaConnect-CSR?node-id=612-171&t=wrhOsbtCmTJ2L0F4-4)

---

## Additional Information

Desktop
![image](https://github.com/user-attachments/assets/1b965a31-df12-4a6e-b321-7cf94dc1fcef)

Mobile
![image](https://github.com/user-attachments/assets/920e70d6-526b-4df8-8c51-ff8700dd0336)

**Comment by gitPirate12** [comment]
ill take this
