### ISSUE TITLE
Implement the footer section

### ISSUE THREAD

**Issue by pawan-live** [sliitsesc/rheumaconnect-fe#25]
## Task Summary

- This is the footer section which is common for the whole site
- This contains links + other contact information relevant for the users to navigate the site
- Implement the desktop as well the mobile views

---

## Acceptance Criteria

- [ ] The background gradient
- [ ] Should follow design specifications given
- [ ] The items under the links blocks should be clickable, keep the links empty for now
- [ ] The phone numbers in the contact section should be clickable as well
- [ ] The data should be loaded from a JSON data file
- [ ] Should be decenlty responsive in all screen sizes

---

Design files: 
- [desktop design](https://www.figma.com/design/Ygf1alhgBbL3IeVSNRQtS7/RheumaConnect-CSR?node-id=398-1088&t=Y8A5MdTDkAF5FbVf-4)

---

## Additional Information

Desktop view
<img width="772" alt="image" src="https://github.com/user-attachments/assets/b0ac72fa-7a77-4062-ae17-32295773a40e" />

Mobile view

**Comment by senithudara** [comment]
can I take this @pawan-live ?

**Comment by pawan-live** [comment]
> can I take this @pawan-live ?
can you do the mobile design for this and implement as well? @senithudara
