### ISSUE TITLE
Implement the category page (dynamic) + header section

### ISSUE THREAD

**Issue by pawan-live** [sliitsesc/rheumaconnect-fe#26]
## Task Summary

- This is the view for an individual main category
- It contains links to sub categories within that main category
- This will be a dynamic page template, should use nextjs dynamic route
- The available routes/pages will be pre-defined (for now use a JSON file, later we'll use the API to get that data)
- The header section title and subtitle will be dynamic too (fetch it from the JSON file for now)

---

## Acceptance Criteria

- [ ] Follow design specification
- [ ] Should be mobile responsive on "md" breakpoint
- [ ] The route should be dynamic, the url slug will decide which page to load
- [ ] Fetch relevant title & description for the header from the JSON file
- [ ] If the slug doesnt match anything given on the pre-defined JSON file, show a text "No category named {slug name}" and show a button to go back to homepage

---

Design files: 
- [desktop](https://www.figma.com/design/Ygf1alhgBbL3IeVSNRQtS7/RheumaConnect-CSR?node-id=398-1126&t=Y8A5MdTDkAF5FbVf-4)
- [mobile](https://www.figma.com/design/Ygf1alhgBbL3IeVSNRQtS7/RheumaConnect-CSR?node-id=612-221&t=Y8A5MdTDkAF5FbVf-4)

---

## Additional Information

Desktop
<img width="806" alt="image" src="https://github.com/user-attachments/assets/bb4b7edf-c1e4-484a-9863-610e7071a4b5" />

Mobile
<img width="463" alt="image" src="https://github.com/user-attachments/assets/7ac42de6-c0c8-4f11-8adb-c25ce4e243b4" />

**Comment by prb-dev** [comment]
I can take this
