### ISSUE TITLE
Implement the Cards section in the category page

### ISSUE THREAD

**Issue by pawan-live** [sliitsesc/rheumaconnect-fe#29]
## Task Summary

- This is the section with cards which is inside an individual main category page (task #26 )
- These cards will link to a page which contains sub-categories related to each main category
- These should be clickable, for now keep the links blank
- The content should be loaded from a JSON file, and also this section should be dynamic
- The content will be fetched from the JSON file in the main category page (#26 ) and passed into this component

<img width="653" alt="image" src="https://github.com/user-attachments/assets/39f85fa2-d1ce-4829-89e7-723698ce42f8" />

---

## Acceptance Criteria

- [ ] Follows design specification
- [ ] Mobile responsive view
- [ ] Hover effect
- [ ] Clickable (link)
- [ ] on mobile, when tapped the hover effect should be triggered

---

Design files: 
- [desktop](https://www.figma.com/design/Ygf1alhgBbL3IeVSNRQtS7/RheumaConnect-CSR?node-id=398-1130&t=n1Lqk3InwGmWfmY3-4)
- [mobile](https://www.figma.com/design/Ygf1alhgBbL3IeVSNRQtS7/RheumaConnect-CSR?node-id=612-228&t=n1Lqk3InwGmWfmY3-4)

---

## Additional Information

desktop
<img width="653" alt="image" src="https://github.com/user-attachments/assets/39f85fa2-d1ce-4829-89e7-723698ce42f8" />

mobile
<img width="313" alt="image" src="https://github.com/user-attachments/assets/04b6691a-5aee-4594-942b-58324d5cab71" />
