### ISSUE TITLE
Implement the language switch menu

### ISSUE THREAD

**Issue by pawan-live** [sliitsesc/rheumaconnect-fe#8]
## Task Summary

- Create the language switch button
- On click it will show the available languages
- Please refer to the design incl. hover effects etc.
- The available languages will be statically stored maybe in a JSON data file, might have plans to fetch from API later
- Upon clicking the new language from the dropdown menu, it should change the selected language in the menu trigger button too

---

## Acceptance Criteria

- [ ] The dropdown appears on click
- [ ] Hover states are implemented
- [ ] When selecting a new language, it switches the language in the menu trigger as well
- [ ] Clicking on anywhere outside the dropdown menu should close the dropdown menu
- [ ] Escape keypress should close the dropdown menu as well
- [ ] Sinhala & Tamil words should be shown in sinhala and tamil languages (make sure to support displaying the text in those languages)
- [ ] On mobile navbar, show the language swwitch menu in the mobile dropdown navbar at the bottom

---

Design files: 
- [link 1](https://www.figma.com/design/Ygf1alhgBbL3IeVSNRQtS7/RheumaConnect-CSR?node-id=509-131&t=Dyzpm6vZj01HWXPl-4)
- [link 2](https://www.figma.com/design/Ygf1alhgBbL3IeVSNRQtS7/RheumaConnect-CSR?node-id=509-189&t=Dyzpm6vZj01HWXPl-4)
- [link 3](https://www.figma.com/design/Ygf1alhgBbL3IeVSNRQtS7/RheumaConnect-CSR?node-id=509-151&t=Dyzpm6vZj01HWXPl-4)

---

## Additional Information

Normal state
![image](https://github.com/user-attachments/assets/c21cd1e9-9e6e-41ba-a407-d2fcc75cf2d7)

On click
![image](https://github.com/user-attachments/assets/ebe1aaae-00d3-4953-9b0c-77133f75a267)

On hovering each link inside
![image](https://github.com/user-attachments/assets/75e17069-9532-4b6c-8fc7-def8aa3845ac)

![image](https://github.com/user-attachments/assets/5efbe15f-7e3a-4289-ab88-41290b330792)

**Comment by prb-dev** [comment]
I'll take this

**Comment by pawan-live** [comment]
This has been implemented in another issue
