### ISSUE TITLE
Implement the hero section of the landing page

### ISSUE THREAD

**Issue by pawan-live** [sliitsesc/rheumaconnect-fe#9]
## Task Summary

- Implement the updated hero section of the landing page
- Including the mobile responsive view as well
- Use tailwind container for container width
- The button will not lead anywhere for now, keep target link '/'

---

## Acceptance Criteria

- [ ] Should follow design styles as given
- [ ] Should be mobile responsive
- [ ] Should support sinhala/tamil languages when language support gets introduced
- [ ] Content will be loaded from a JSON data store initially, later should be able to fetch from API (strapi) with internationalization support

---

Design files: 
- [desktop](https://www.figma.com/design/Ygf1alhgBbL3IeVSNRQtS7/RheumaConnect-CSR?node-id=526-170&t=F7jJtMRCQmT5mUnr-4)
- [mobile](https://www.figma.com/design/Ygf1alhgBbL3IeVSNRQtS7/RheumaConnect-CSR?node-id=521-1024&t=F7jJtMRCQmT5mUnr-4)

---

## Additional Information

Desktop view
<img width="710" alt="image" src="https://github.com/user-attachments/assets/653f680b-be7d-4237-a869-3736ba3458e6" />

Mobile view
<img width="323" alt="image" src="https://github.com/user-attachments/assets/af853977-2d79-4ca2-9949-3b26e9f94fe4" />

Multilingual example
<img width="743" alt="image" src="https://github.com/user-attachments/assets/22cd1cb4-4568-47b3-ba7e-43bc86285430" />

**Comment by IT21182914** [comment]
I will take this

**Comment by IT22202468** [comment]
I see the horizontal margins are not even here as in the Figma design. Also the space between lines are closer. 

Check this @IT21182914 

![Screenshot 2024-12-24 193634](https://github.com/user-attachments/assets/5e078d35-ba1f-43ee-93d7-9fea52e7ed20)
